### ISSUE TITLE
Model Embeddings, Interpretation of the Prototypes & Evaluation

### ISSUE THREAD

**Issue by adrian-jaques-b** [zhpinkman/prototex_custom#1]
Hello,
First of all, thank you for sharing your code!
I'm implementing your code because I want to use it for my master thesis. 
More, specifically, I want to use a bert-base-uncased model for generating prototypes for transformer explainability. 
I encountered some questions you might can answer:

1. I found in your code an adaption for a RoBERTa model. I use this code for my bert model. However, in some of the functions for inference (for ex. `get_best_k_protos_for_batch()`)  for calculating the embeddings `last_hidden_state = model_new.bart_model.base_model.encoder() `in used. 

Since this is for the BART model that was implemented in the source code, I'm wondering if it is accurate to change it to: `last_hidden_state = model_new.bert_model()` ? 
Have you implemented it somewhere for the RoBERTa model and I'm just missing it?

I also tried it with` last_hidden_state = model_new.bert_model.encoder()` but that gave me several mismatch errors. 
My ProtoTRex model looks like that: 
```
My ProtoTRex model looks like that: 
ProtoTEx_roberta(
  (bert_model): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (classfn_model): Linear(in_features=20, out_features=2, bias=False)
  (loss_fn): CrossEntropyLoss()
  (dropout): Dropout(p=1, inplace=False)
)
```
I get some results using my solution but I'm not sure if I'm doing it right. I hope you can help me to clarify that. 

2. Since I need it for a binary (and maybe a multiclass) problem I was wondering if you could provide some example results of your experiments so I can check if my output seems legit. 
3. This question is kind of related to the second one.
 The output I get / the first few Prototypes are the same for every sentence. So I'm not sure if that is how the results should look like. 
The Prototypes just start getting different at the colum "Prototype_1_Nearest_train_eg_0".
Here is the .CSV file to you can have a look:
[ProtoTEx_bert-base-uncased_nearest_1.csv](https://github.com/zhpinkman/prototex_custom/files/11301162/ProtoTEx_bert-base-uncased_nearest_1.csv)
4. In your paper you just evaluated the classification results of the method right? I would like to evaluate the method more with the focus on the explainability perspective by doing a human evalution. I know how Das et al. proceed in the original paper, but since I can't find anything for that perspective in you paper, I was wondering if you have thought about some methods that I could use?

Sorry for all those questions but this is very important for me since I need it for graduating. 

Thank you so much!
Jaqu

**Comment by zhpinkman** [comment]
Hello @JaquJaqu 
Thanks for your interest and also using our code,

Actually, the code is way cleaner in this stage of my development, so maybe you want to check the implementation again. But in general, language models are only responsible for getting the embeddings or any sort of representation from the text. so you can change that part of the code accordingly. In other words, It doesn't necessarily have to be a BART, BERT, or ROBERTA. I'll be more than happy to help if you want to change anything in the code. (you can also email me at zhivarsourati@gmail.com directly). I've changed the code so that it can handle different tasks with different output numbers, such as a binary or a multi-class classification task in general. With regard to your question about the explainability of the method, you can check our paper (https://arxiv.org/abs/2212.07425). We did a qualitative analysis on the explainability of the prototype-based methods on the task of logical fallacy identification, let me know if that is helpful. 

Sorry for the late response, I hope the email would help in case of any other questions. 
Best,
Zhivar
